name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet packages
      run: nuget restore Source/Zombiefied.sln

    - name: Build
      run: msbuild Source/Zombiefied.sln /p:Configuration=Release

    - name: Upload Preview Mod
      uses: actions/upload-artifact@v2
      with:
        name: Zombiefied
        path: |
          About
          Assemblies
          Defs
          !HugsLib*
          !0Harmony*
